source "http://rubygems.org"
source "http://gemcutter.org"
gem "rails", "= 2.3.10"
gem "rake"
gem "test-spec"
gem "rspec"
gem "rspec-rails"
gem "hpricot"
gem "libxml-ruby"
gem "syntax"
gem "verhoeff"
gem "aasm"
